### ISSUE TITLE
SQL connection error

### ISSUE THREAD

**Issue by emwardell** [beiyiz/Steton#1]
Could you create a Readme.md file for this project with instructions on how to configure the project so it will not throw an error at startup?

The error is:
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

**Comment by beiyiz** [comment]
Please use the script in https://github.com/beiyiz/Steton/tree/master/SQL%20Scripts to create the database.

In ElevatorSimulationRepository project, change the database connection string with the correct instance you created in the settings.

**Comment by beiyiz** [comment]
In the ElevatorSimulationUI project, location app.js file in the js folder,  you will need to change $rootScope.baseApiAddress = 'http://localhost:47783/api' to the address your api will be run on.

**Comment by emwardell** [comment]
Thank you!
